apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb-deployment
  labels:
    app: dynamodb
spec:
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
        - name: dynamodb
          image: amazon/dynamodb-local
          ports:
            - containerPort: 443
